/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Sthlm1646RouteImport } from './routes/sthlm1646'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OurGamesRouteImport } from './routes/our-games'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameUpdatesIndexRouteImport } from './routes/game-updates/index'
import { Route as GameUpdatesSlugRouteImport } from './routes/game-updates/$slug'

const Sthlm1646Route = Sthlm1646RouteImport.update({
  id: '/sthlm1646',
  path: '/sthlm1646',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OurGamesRoute = OurGamesRouteImport.update({
  id: '/our-games',
  path: '/our-games',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameUpdatesIndexRoute = GameUpdatesIndexRouteImport.update({
  id: '/game-updates/',
  path: '/game-updates/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameUpdatesSlugRoute = GameUpdatesSlugRouteImport.update({
  id: '/game-updates/$slug',
  path: '/game-updates/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/our-games': typeof OurGamesRoute
  '/privacy': typeof PrivacyRoute
  '/sthlm1646': typeof Sthlm1646Route
  '/game-updates/$slug': typeof GameUpdatesSlugRoute
  '/game-updates/': typeof GameUpdatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/our-games': typeof OurGamesRoute
  '/privacy': typeof PrivacyRoute
  '/sthlm1646': typeof Sthlm1646Route
  '/game-updates/$slug': typeof GameUpdatesSlugRoute
  '/game-updates': typeof GameUpdatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/our-games': typeof OurGamesRoute
  '/privacy': typeof PrivacyRoute
  '/sthlm1646': typeof Sthlm1646Route
  '/game-updates/$slug': typeof GameUpdatesSlugRoute
  '/game-updates/': typeof GameUpdatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/community'
    | '/our-games'
    | '/privacy'
    | '/sthlm1646'
    | '/game-updates/$slug'
    | '/game-updates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/community'
    | '/our-games'
    | '/privacy'
    | '/sthlm1646'
    | '/game-updates/$slug'
    | '/game-updates'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/community'
    | '/our-games'
    | '/privacy'
    | '/sthlm1646'
    | '/game-updates/$slug'
    | '/game-updates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommunityRoute: typeof CommunityRoute
  OurGamesRoute: typeof OurGamesRoute
  PrivacyRoute: typeof PrivacyRoute
  Sthlm1646Route: typeof Sthlm1646Route
  GameUpdatesSlugRoute: typeof GameUpdatesSlugRoute
  GameUpdatesIndexRoute: typeof GameUpdatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sthlm1646': {
      id: '/sthlm1646'
      path: '/sthlm1646'
      fullPath: '/sthlm1646'
      preLoaderRoute: typeof Sthlm1646RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-games': {
      id: '/our-games'
      path: '/our-games'
      fullPath: '/our-games'
      preLoaderRoute: typeof OurGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-updates/': {
      id: '/game-updates/'
      path: '/game-updates'
      fullPath: '/game-updates/'
      preLoaderRoute: typeof GameUpdatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-updates/$slug': {
      id: '/game-updates/$slug'
      path: '/game-updates/$slug'
      fullPath: '/game-updates/$slug'
      preLoaderRoute: typeof GameUpdatesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommunityRoute: CommunityRoute,
  OurGamesRoute: OurGamesRoute,
  PrivacyRoute: PrivacyRoute,
  Sthlm1646Route: Sthlm1646Route,
  GameUpdatesSlugRoute: GameUpdatesSlugRoute,
  GameUpdatesIndexRoute: GameUpdatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
